import { Poppins } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/LandingPage/Header";
import PageTransition from "@/components/LandingPage/PageTransition";
import { ThemeProvider } from "next-themes";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Kennys Professional Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <ThemeProvider enableSystem={true} attribute="class">
        <Header />
        <PageTransition> {children}</PageTransition>
        </ThemeProvider>
      </body>
    
    </html>
  );
}
